version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - app
    ports:
      - 8080:80
  db:
    image: postgres:11-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: bananapotato
      POSTGRES_USER: acbw
      POSTGRES_DB: rails_test_app
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=postgres://acbw:bananapotato@db
        # the one below is a hack, remove this when using nginx
      - RAILS_SERVE_STATIC_FILES=true
