version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - asset-volume:/var/www/html
  db:
    image: postgres:11-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - asset-volume:/app/public
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=${DATABASE_URL}
        # the one below is a hack, remove this when using nginx
      # - RAILS_SERVE_STATIC_FILES=true
      - RAILS_ENV=production
volumes:
  asset-volume:
