version: '3'
services:
  db:
    image: postgres:11-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: bananapotato
      POSTGRES_USER: acbw
      POSTGRES_DB: rails_test_app
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: ./dockerfile/app/Dockerfile
    command: >
      sh -c "rake assets:precompile
      && bundle exec rails s -p 3000 -b '0.0.0.0' --environment=production"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=postgres://postgres@db
        # the one below is a hack, remove this when using nginx
      - RAILS_SERVE_STATIC_FILES=true
